<?php
/**
 * Copyright (C) 2026 Benjamin Rosenberger <bensch.rosenberger@gmail.com>
 *
 * @copyright 2026 Benjamin Rosenberger
 * @author bensch.rosenberger@gmail.com
 * @license MIT
 * @link https://brocode.at
 */
declare(strict_types=1);

/** @var \BroCode\GridFilterSort\Block\Adminhtml\PageConfig $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php if ($block->hasWhitelist()): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        'window.brocodeGridFilterSortWhitelist = ' . $block->getWhitelistJson() . ';',
        false
    ) ?>
<?php endif; ?>
